### PR TITLE
Added AWS Lambda Credential Function

### PR DESCRIPTION
**Pull request by This-Is-Not-Brad**
Added config function to allow for easier integration from AWS Lambda, removing the need to pass in hard-coded Access Keys and Secret Keys.

### CODE REVIEW

**Comment by henrywu2019** [comment]
Thank @This-Is-Not-Brad for the PR. Actually, there are four functions in https://github.com/uber/athenadriver/blob/master/examples/auth.go to authenticate a user. The last three functions don't require you to input access key and id. Can we use one of the three functions in your Lambda? May I know why this PR is required for a Lambda function? Thank you very much.

**Comment by This-Is-Not-Brad** [comment]
> Thank @This-Is-Not-Brad for the PR. Actually, there are four functions in https://github.com/uber/athenadriver/blob/master/examples/auth.go to authenticate a user. The last three functions don't require you to input access key and id. Can we use one of the three functions in your Lambda? May I know why this PR is required for a Lambda function? Thank you very much.

Hey Henry,

The first example ' useAthenaDriverConfigForAuth() 'does not work, as you still need to provide a secret key \ access key.

The last 3 examples, use the credentials which are stored in credential\profile files, which do not exist in AWS Lambda.

**Comment by henrywu2019** [comment]
> > Thank @This-Is-Not-Brad for the PR. Actually, there are four functions in https://github.com/uber/athenadriver/blob/master/examples/auth.go to authenticate a user. The last three functions don't require you to input access key and id. Can we use one of the three functions in your Lambda? May I know why this PR is required for a Lambda function? Thank you very much.
> 
> Hey Henry,
> 
> The first example ' useAthenaDriverConfigForAuth() 'does not work, as you still need to provide a secret key \ access key.
> 
> The last 3 examples, use the credentials which are stored in credential\profile files, which do not exist in AWS Lambda.

This is an interesting use case. Thanks a lot @This-Is-Not-Brad . 

From the PR, it seems `session.NewSession` will work in Lambda with only `region` provided. How about you just pass some dummy/empty strings as access id and key in `useAthenaDriverConfigForAuth` in Amazon Lambda, will that work?

**Comment by henrywu2019** [comment]
I just tested athenadriver in lambda. Actually you can use the second function in `auth.go` to make it work. The code I used is:

```
	os.Setenv("AWS_SDK_LOAD_CONFIG", "1")
	conf, err := drv.NewDefaultConfig("s3://mytestbucket/", drv.DefaultRegion, drv.DummyAccessID, drv.DummySecretAccessKey)
```

Thanks a lot @This-Is-Not-Brad . I will update the document to include the lambda use case.

**Pull request closed without merging**
